# Generated by Django 2.0 on 2017-12-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('address', models.CharField(max_length=80, null=True, verbose_name='地址')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name=' 邮箱')),
            ],
        ),
    ]
