# Generated by Django 2.0 on 2017-12-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='qq',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
