# Generated by Django 2.0 on 2017-12-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0003_addressbook_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'permissions': (('view_address', 'View address'),)},
        ),
    ]
