# Generated by Django 2.0 on 2017-12-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0004_auto_20171218_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={},
        ),
    ]
